Repository okaryo/lazy_load_indexed_stack, pull requests merged in 2025-01, with the labels that each got.

#9 Add release.yml to categorize release notes by pull request labels
  .github/release.yml
Labels: documentation

#7 Add `autoDisposeIndexes` to dispose unused IndexedStack children and rebuild them when needed
  README.md
  lib/lazy_load_indexed_stack.dart
Labels: feature

#12 Fix issue where non-preloaded children were loaded when index changed
  README.md
  lib/lazy_load_indexed_stack.dart
  test/lazy_load_indexed_stack_test.dart
Labels: bug
